remote_theme: vyncem/minimal-mistakes


markdown: kramdown

collections_dir: .
collections:
    articles:
      output: true
      
name: rip

site:
    name: rip.ke

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
